# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

variables: 
  pathToTest: $(Build.Repository.LocalPath)/$(Build.SourceBranchName)/test

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    mkdir -p $(Build.Repository.LocalPath)/$(Build.SourceBranchName)/test
    mkdir -p '$(pathToTest)/testPath'
    cd  $(Build.Repository.LocalPath)/$(Build.SourceBranchName)/test
    echo text.html
    ls
    
    

  displayName: 'npm install and build'

#    mkdir -p $(Build.Repository.LocalPath)/$(Build.SourceBranchName)/testBranchName
#    mkdir -p $(Build.Repository.LocalPath)/$(Build.PullRequest.TargetBranchName)/testTargetBranch
#    mkdir -p $(Build.Repository.LocalPath)/$(Build.SourceBranch)/testSourceBranch
# echo $(Build.Repository.LocalPath)/$(Build.PullRequest.TargetBranchName)/test